“””
Shblood Social Media Links Manager
ئەم سکریپتە بۆ بەڕێوەبردنی لینکەکانی سۆشیاڵ میدیا و دروستکردنی فایلی JSON
“””

import json
import os

class ShbloodLinksManager:
def **init**(self, config_file=‘shblood_config.json’):
self.config_file = config_file
self.links = self.load_config()

```
def load_config(self):
    """بارکردنی کۆنفیگی لینکەکان لە فایلی JSON"""
    if os.path.exists(self.config_file):
        with open(self.config_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    else:
        # لینکەکانی بنەڕەت
        return {
            "tiktok": "https://www.tiktok.com/@shblood",
            "telegram": "https://t.me/shblood",
            "footer_telegram": "https://t.me/shblood",
            "website_name": "Shblood",
            "welcome_message": "بەخێربێیت بۆ وێبسایتی شابڵۆد",
            "description": "ئێرە وێبسایتی فەرمی شابڵۆدە",
            "join_message": "جۆین بن هیوای سوود گەیاندن",
            "footer_message": "ئەم وێبسایتە پارێزراوە بۆ چەناڵی شابڵۆد"
        }

def save_config(self):
    """پاشەکەوتکردنی کۆنفیگ لە فایلی JSON"""
    with open(self.config_file, 'w', encoding='utf-8') as f:
        json.dump(self.links, f, ensure_ascii=False, indent=4)
    print(f"✓ کۆنفیگ پاشەکەوت کرا لە {self.config_file}")

def update_link(self, platform, new_url):
    """نوێکردنەوەی لینکێک"""
    if platform in self.links:
        self.links[platform] = new_url
        print(f"✓ لینکی {platform} نوێکرایەوە بۆ: {new_url}")
    else:
        print(f"✗ پلاتفۆرمی {platform} نەدۆزرایەوە")

def update_text(self, field, new_text):
    """نوێکردنەوەی دەقەکان"""
    if field in self.links:
        self.links[field] = new_text
        print(f"✓ {field} نوێکرایەوە")
    else:
        print(f"✗ خانەی {field} نەدۆزرایەوە")

def display_config(self):
    """پیشاندانی کۆنفیگی ئێستا"""
    print("\n" + "="*50)
    print("کۆنفیگی ئێستای Shblood")
    print("="*50)
    for key, value in self.links.items():
        print(f"{key}: {value}")
    print("="*50 + "\n")

def export_to_js(self, output_file='links_config.js'):
    """هەناردەکردنی کۆنفیگ بۆ فایلی JavaScript"""
    js_content = f"""// Generated by Shblood Links Manager
```

const shbloodConfig = {json.dumps(self.links, ensure_ascii=False, indent=4)};

// بەکارهێنان:
// document.getElementById(‘tiktok-link’).href = shbloodConfig.tiktok;
“””
with open(output_file, ‘w’, encoding=‘utf-8’) as f:
f.write(js_content)
print(f”✓ کۆنفیگی JavaScript دروستکرا لە {output_file}”)

def main():
“”“فەنکشنی سەرەکی”””
manager = ShbloodLinksManager()

```
print("به‌رنامه‌ی به‌ڕێوه‌بردنی لینکه‌کانی Shblood")
print("-" * 50)

while True:
    print("\n1. پیشاندانی کۆنفیگی ئێستا")
    print("2. نوێکردنەوەی لینکی TikTok")
    print("3. نوێکردنەوەی لینکی Telegram")
    print("4. نوێکردنەوەی دەقەکان")
    print("5. پاشەکەوتکردنی گۆڕانکارییەکان")
    print("6. هەناردەکردن بۆ JavaScript")
    print("7. دەرچوون")
    
    choice = input("\nهەڵبژاردەکەت بنووسە (1-7): ")
    
    if choice == '1':
        manager.display_config()
    
    elif choice == '2':
        new_url = input("لینکی نوێی TikTok: ")
        manager.update_link('tiktok', new_url)
    
    elif choice == '3':
        new_url = input("لینکی نوێی Telegram: ")
        manager.update_link('telegram', new_url)
        manager.update_link('footer_telegram', new_url)
    
    elif choice == '4':
        print("\nدەقی بگۆڕە:")
        print("a. ناوی وێبسایت")
        print("b. پەیامی بەخێربێیت")
        print("c. پەیامی جۆین")
        sub_choice = input("هەڵبژاردە: ")
        
        if sub_choice == 'a':
            new_text = input("ناوی نوێ: ")
            manager.update_text('website_name', new_text)
        elif sub_choice == 'b':
            new_text = input("پەیامی نوێی بەخێربێیت: ")
            manager.update_text('welcome_message', new_text)
        elif sub_choice == 'c':
            new_text = input("پەیامی نوێی جۆین: ")
            manager.update_text('join_message', new_text)
    
    elif choice == '5':
        manager.save_config()
    
    elif choice == '6':
        manager.export_to_js()
    
    elif choice == '7':
        print("سوپاس! خواحافیز")
        break
    
    else:
        print("هەڵبژاردەی نادروست!")
```

if **name** == “**main**”:
main()